version: '3.8'

services:
  app:
    image: edobxt/oceane-svr-portfolio:latest
    container_name: oceane-svr-portfolio
    working_dir: /var/www/html
    command: php -S 0.0.0.0:3880 -t .
    ports:
      - "3880:3880"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb
    container_name: oceane-svr-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: monportfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: oceane-svr-pma
    ports:
      - "3888:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
